# Generated by Django 5.0.7 on 2024-09-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('text_field', models.CharField(blank=True, max_length=5000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('img_file', models.FileField(blank=True, null=True, upload_to='img/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
        ),
    ]
